### ISSUE TITLE
Branch-protection updated added wrong status checks

### ISSUE THREAD

**Issue by tkilias** [exasol/github-keeper#38]
In https://github.com/exasol/sagemaker-extension[sagemaker-extension](https://github.com/exasol/sagemaker-extension) our PR expect builds which never get executed. 

![Screenshot from 2021-11-29 17-09-02](https://user-images.githubusercontent.com/5796845/143903347-bd7622be-d4f7-4702-9fe6-21fa9e15d21c.png)

We checked the branch protection was updated by Github-Keeper

![Screenshot from 2021-11-29 17-09-45](https://user-images.githubusercontent.com/5796845/143903583-249d1b5e-e376-4917-8449-a363b7012514.png)

Here is a link to a PR in the project:

https://github.com/exasol/sagemaker-extension/pull/43

**Comment by jakobbraun** [comment]
Could you please try to remove the protection, rerun latest github-keeper on the project and check if it's fixed?

**Comment by pj-spoelders** [comment]
Bumped @tkilias

**Comment by tkilias** [comment]
ok, I tried it, I think, it works now
