### ISSUE TITLE
Migrate github-repo check(s) from  product-integration-tool-chest to github-keeper

### ISSUE THREAD

**Issue by Nicoretti** [exasol/github-keeper#52]
Implement/Validate that `github-keeper` supports "all" the aspects of what [product-integration-tool-chest](https://github.com/exasol/product-integration-tool-chest) supports regarding github features.

Once the feature set is supported by `github-keeper` the `product-integration-tool-chest` related code can be removed and the project can reference `github-keeper` for this functionality.

Related Issues:
 * exasol/product-integration-tool-chest#40

**Comment by ckunki** [comment]
The current ticket has been superseded by migration to [github-issue-adapter](https://github.com/exasol/github-issue-adapter).
See [minutes for meeting on 2023-02-06](https://exasol.atlassian.net/wiki/spaces/InTeam/pages/80412732/2023-02-06+Unify+Scripts+for+GitHub+automation) and in particular ticket https://github.com/exasol/github-issue-adapter/issues/69.
