### ISSUE TITLE
github-keeper fails with stacktrace for no obvious reason

### ISSUE THREAD

**Issue by Nicoretti** [exasol/github-keeper#59]
# Details
github-keeper crashes with no obvious reason.

![screenshot](https://user-images.githubusercontent.com/600911/179214087-f4241531-9965-42b0-a9f0-e5f2358a4456.png)

## Steps to reproduce
1. Setup a `projekt-keeper` credentials file with outdated/invalid github credentials
2. Execute github-keeper
 
## Expected behavior
`github-keeper` is reporting that the credentials are invalid and should be updated.

## Actual behavior
`github-keeper` crashes with a stacktrace

## Root Cause
root cause seems to be the usage of expired github credentials (e.g. gh token). 

## Note
:warning: Apparently `github-keeper` is retrieving the credentials from the `project-keeper` credentials file, this is far from being obvious.

| Tools | strategy |
|-------|----------|
| [release-droid](https://github.com/exasol/release-droid) | file `~/.release-droid/credentials` |
| [github-keeper](https://github.com/exasol/github-keeper/blob/main/cmd/githubClientProvider.go#L24) | file `~/.release-droid/credentials` |
| [product-integration-tool-chest / python](https://github.com/exasol/product-integration-tool-chest/blob/main/utils/accessTokenReader.py) | file `~/.release-droid/credentials` |
| [product-integration-tool-chest / shell scripts](https://github.com/exasol/product-integration-tool-chest) |   uses tool `gh`, which evaluates environment variable `GH_TOKEN` |
| [project-overview](https://github.com/exasol/project-overview/blob/main/query/auth.go#L18) | environment variable `GITHUB_TOKEN` |
| [project-keeper](https://github.com/exasol/project-keeper/) | (no access to github, yet) |
| Build scripts, generated by [project-keeper](https://github.com/exasol/project-keeper/) | environment variable `GITHUB_TOKEN` |

**Comment by Nicoretti** [comment]
Consider adding [keyring](https://github.com/zalando/go-keyring) for storing the secret(s).

**Comment by ckunki** [comment]
Hello @Nicoretti, [cmd/githubClientProvider.go](https://github.com/exasol/github-keeper/blob/main/cmd/githubClientProvider.go#L29)  evaluates `~/.release-droid/credentials`.

keyring could raise the question how to support java applications such as release droid.
How should we proceed here?

**Comment by Nicoretti** [comment]
@ckunki a good error message if the `release-droid/credentails` file is missing would be the bare minimum.
It is far from obvious that `github-keeper` needs the credential file of another tool.

**Comment by ckunki** [comment]
Hi Nico, I definitely agree to a good error message as bare minimum.
I must admit that I still feel to have too little understanding about how closely different tools are linked if such a linkage is desired or should be avoided.

**Comment by ckunki** [comment]
I found more linked tools, see main description of the ticket.

**Comment by Nicoretti** [comment]
A more sophisticated strategy definitely would help. Still the major issue in my opinion is that the configuration file of another tool is used. Having a general config file for common settings of our tooling e.g. `.config/exasol/tools/config.ini` would be the cleanest solution besides using the keyring. As a migration strategy we could support both, old and new config file location and issue a warning if only the old one contains a config. This would enable us to migrate the dependent tools individually.
